spring:
  rabbitmq:
    host: 192.168.11.211
    port: 5672
  sleuth:
    enabled: false
  collector:
    base-url: http://hap-zipkin-ui:9411/
  cloud:
    config:
      allowOverride: true
      failFast: true
      overrideNone: false
      overrideSystemProperties: false
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
