spring:
  datasource:
    url: jdbc:mysql://192.168.11.172:16408/cloud_afwk?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cloudafwk
    password: handhand
  redis:
    host: 192.168.11.201
    port: 6379
    clientName: API-GATEWAY
    database: 2
    dftExpire: 600
    lockDatabase: 3
  rabbitmq:
    host: 192.168.11.210
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    listener:
      acknowledge-mode: MANUAL
scurity:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxhlV3wv8rMFafzglAKqc
          7G0ZaUFeEnDeuB7LiMmPLvydOREbQj3hdp8JEkISAOlKObdDYadvtbM9JMTwEh/6
          QZh+2wx2cbQ7F/RAUeCFqU1qRF+LvTSArLZc2f48t1KvsbcAhQUwcVMe5ukhNe//
          CfIY6mlCFUWZdvw61yDiDnJ7dkwXaQdYdcgUzvSv754DB8xZV4iJdLlwXixfRTFh
          6pQ8xpGxcaETNEwRkBi2dLBFYjfBhgh5lpvO8RYcKbnrKKA0VJ4/GamYT2mxjMuP
          k+jsVVcOqpDKIwXZ00jxIN96PKVNXMFa6Dm2IPv15iaVcyN041EdB/+3plg0+ZsC
          4QIDAQAB
          -----END PUBLIC KEY-----
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 120000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true

context:
    listener:
        classes:
         com.hscf.cloud.afwk.redis.CacheMessageListener
hcloud:
    domain:
        scf: http://scfuat.hjl.hscf.com/yyy
        auth: https://uat.hjl.hscf.com/
        rms: https://rmsuat.hscf.com/

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 10000

